# Generated by Django 4.2.6 on 2023-10-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(unique=True, verbose_name='Tg chat id'),
        ),
    ]
