# Generated by Django 4.2.6 on 2023-10-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('time', models.TimeField(verbose_name='Time of start')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Action')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='Period(days)')),
                ('duration_of_action', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration of action')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Is pleasant habit')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Reward for the completed action')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public habit')),
                ('last_reminder', models.DateTimeField(blank=True, null=True, verbose_name='Last reminder')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='Connected habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
