# Generated by Django 4.2.6 on 2023-10-22 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Локация')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('action', models.TextField(verbose_name='Действие')),
                ('period', models.IntegerField(default=1, verbose_name='Периодичность привычки')),
                ('duration_of_action', models.IntegerField(verbose_name='Длительность привычки в секундах')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение за выполнение действия')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности привычки')),
                ('last_reminder', models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
